### ISSUE TITLE
Request to Add Licence

### ISSUE THREAD

**Issue by maheshwari-1153** [rvamsikrishna/flutter_ui_challenge_planets_app#4]
Hello,

I am Maheshwari from team [GeekyAnts](https://geekyants.com/). On behalf of [Start Flutter](https://startflutter.com/), we add open source products which we find helpful to the community & also we provide credits to author itself.
Let me know if you are interested showcase your product in our open source website. If yes, then I request you to add MIT Licence in your repo.
Looking forward to hear from you.

**Comment by rvamsikrishna** [comment]
Thank you very much, Maheshwari of reaching out. I've been a bit busy these past days. I am interested in showcasing my project in your opensource website. I've added the MIT license.

**Comment by maheshwari-1153** [comment]
Hello,

Thanks for letting me know. I will check & get back to you.

Best Regards,
Maheshwari Shukla

**Comment by maheshwari-1153** [comment]
Hello,

I have added your product in Start-Flutter-Website
<https://startflutter.com/themes/flutter-based-planets-app/>. Please have a
look at it.

Feel free to contact me if you have any questions.

Best Regards,
Maheshwari Shukla

**Comment by rvamsikrishna** [comment]
Thank you for adding the project and showcasing it on your website.
